"""Constants for the Panasonic H&C integration."""

DOMAIN = "panasonic_hc"

MANUFACTURER = "Panasonic"
MODEL = "CZ-RTC6BLW"

SIGNAL_THERMOSTAT_DISCONNECTED = f"{DOMAIN}.thermostat_disconnected"
SIGNAL_THERMOSTAT_CONNECTED = f"{DOMAIN}.thermostat_connected"

# Configuration constants
CONF_RECONNECT_BASE_DELAY = "reconnect_base_delay"
CONF_RECONNECT_MAX_DELAY = "reconnect_max_delay"
CONF_NOTIFICATION_TIMEOUT = "notification_timeout"
CONF_TEMP_CHANGE_THRESHOLD = "temp_change_threshold"
CONF_TEMP_VALIDATION_WINDOW = "temp_validation_window"
CONF_TEMP_VALIDATION_ENABLED = "temp_validation_enabled"
CONF_STATUS_UPDATE_INTERVAL = "status_update_interval"
CONF_CONSUMPTION_UPDATE_INTERVAL = "consumption_update_interval"

# Default values
DEFAULT_RECONNECT_BASE_DELAY = 2
DEFAULT_RECONNECT_MAX_DELAY = 30
DEFAULT_NOTIFICATION_TIMEOUT = 20
DEFAULT_TEMP_CHANGE_THRESHOLD = 10.0
DEFAULT_TEMP_VALIDATION_WINDOW = 10.0
DEFAULT_TEMP_VALIDATION_ENABLED = True
DEFAULT_STATUS_UPDATE_INTERVAL = 10
DEFAULT_CONSUMPTION_UPDATE_INTERVAL = 300